// <auto-generated />
using System;
using E_Commerce_Outdoorways.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Outdoorways.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Men"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Women"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kids"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Autumn"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Winter"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Spring"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Summer"
                        });
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Price = 129.99m,
                            ProductDesc = "High-quality winter jacket designed for extreme cold. Warm, durable and perfect for outdoor adventures.",
                            ProductIMG = "jacket1.jpg",
                            ProductName = "Men Winter Jacket",
                            ProductQty = 20
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Price = 149.99m,
                            ProductDesc = "Premium women’s winter coat crafted for warmth, comfort and style. Ideal for harsh winter conditions.",
                            ProductIMG = "coat1.jpg",
                            ProductName = "Women Winter Coat",
                            ProductQty = 15
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Price = 39.99m,
                            ProductDesc = "Soft and comfortable hoodie for kids. Perfect for school, play, or layering on chilly days.",
                            ProductIMG = "hoodie.jpg",
                            ProductName = "Kids Hoodie",
                            ProductQty = 30
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Price = 49.99m,
                            ProductDesc = "Classic autumn flannel shirt made from breathable cotton. A warm and stylish choice for the fall season.",
                            ProductIMG = "flannel.jpg",
                            ProductName = "Autumn Flannel Shirt",
                            ProductQty = 40
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Price = 19.99m,
                            ProductDesc = "Insulated thermal gloves for maximum warmth. Ideal for winter sports, hiking, and everyday use.",
                            ProductIMG = "gloves.jpg",
                            ProductName = "Winter Thermal Gloves",
                            ProductQty = 50
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            Price = 69.99m,
                            ProductDesc = "Lightweight spring jacket designed for mild weather. Wind-resistant and comfortable for outdoor activities.",
                            ProductIMG = "lightjacket.jpg",
                            ProductName = "Spring Light Jacket",
                            ProductQty = 22
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 7,
                            Price = 15.99m,
                            ProductDesc = "Breathable, comfortable summer t-shirt made from soft cotton. Perfect for hot days and outdoor adventures.",
                            ProductIMG = "tshirt.jpg",
                            ProductName = "Summer T-Shirt",
                            ProductQty = 60
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 7,
                            Price = 24.99m,
                            ProductDesc = "Light and durable summer shorts designed for maximum comfort. Ideal for hiking, beach, and casual wear.",
                            ProductIMG = "shorts.jpg",
                            ProductName = "Summer Shorts",
                            ProductQty = 45
                        });
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "realiriccardo05@gmail.com",
                            FullName = "Riccardo Reali",
                            Password = "W_Back_End",
                            Type = "Admin"
                        });
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Order", b =>
                {
                    b.HasOne("E_Commerce_Outdoorways.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.OrderItem", b =>
                {
                    b.HasOne("E_Commerce_Outdoorways.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Outdoorways.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Product", b =>
                {
                    b.HasOne("E_Commerce_Outdoorways.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Outdoorways.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
